server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/yc-app?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  freemarker:
    cache: false
    settings:
      template_update_delay: 1ms
    suffix: .html
    template-loader-path: classpath:/templates/

workde:
  secure:
    enable: false
    skip:
      - /hello
  qiniu:
    accessKey: 8lWMD94lchZIwft7_Q87rtP9wBG5-dbHobONTdvf   #上传key
    secretKey: AJ1Jyhr9fzOME-MART4Btgh5OuC6TLUVvQZJ6ePF   #上传秘钥
    bucket: ydool         #上传空间
