server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.56/ydool-feed-app?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  freemarker:
    cache: false
    settings:
      template_update_delay: 1ms
      tag_syntax: auto_detect
      defaultEncoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
      boolean_format: true, false
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      number_format: 0.######
      whitespace_stripping: true
      classic_compatible: true
      auto_import: ftl/index.ftl as ui, ftl/spring.ftl as s
    suffix: .html
    template-loader-path: classpath:/templates/

workde:
  secure:
    enable: false
    skip:
      - /hello
  qiniu:
    accessKey: 8lWMD94lchZIwft7_Q87rtP9wBG5-dbHobONTdvf   #上传key
    secretKey: AJ1Jyhr9fzOME-MART4Btgh5OuC6TLUVvQZJ6ePF   #上传秘钥
    bucket: ydool         #上传空间
