server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/yc-app?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

workde:
  secure:
    skip:
      - /hello

logging:
  level:
    cn.workde.core.sample.boot.mapper: DEBUG
