server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.56/ydool-feed-app?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

workde:
  serverId: '00'
