<#include "ftl/ui/table.ftl"/>
<#include "ftl/ui/column.ftl"/>
<#include "ftl/ui/page.ftl"/>
<#include "ftl/ui/field.ftl"/>
<#include "ftl/ui/text.ftl"/>
<#include "ftl/ui/select.ftl"/>
<#include "ftl/ui/radio.ftl"/>
<#include "ftl/ui/textarea.ftl"/>
<#include "ftl/ui/switch.ftl"/>
